import Head from 'next/head'
import { ReactNode } from 'react'
import { Toaster } from 'react-hot-toast'
import { Header } from './Header'

interface PageTitle{
    title: string,
    children: ReactNode
}
export default function Layout({title, children}:PageTitle){
    return <>
        <Head>
          <title>{title}</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        {/* toaster */}
        <Toaster
        position="top-center"
        reverseOrder={false}
        />
        {/* header */}
        <Header />

        {/* body */}
        <div>
            {children}    
        </div>
        
        {/* footer */}
    </>
}