import {ProductDetails} from '@/components/ProductDetails'
import { useRouter } from 'next/router'
import Head from 'next/head'


export default function Product() {
  
  const router = useRouter()
  const { handle } = router.query
  if (!handle){
    return <></>
  }
  return (
    <> 
      <Head>
          <title>{handle}</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <ProductDetails handle={`${handle}`} />
    </>
  )
}


